### ISSUE TITLE
Structure layout of the mobile design

### ISSUE THREAD

**Issue by mia-jane** [mia-jane/sunnyside-agency-landing-page#1]
## Tasks
- [x] structure contents of the html boiler plate into divs
- [x] add images to html file 
- [x] create styles.css and link to html file
- [x] css style main section layout

#### Time estimate
4 hours
