### ISSUE TITLE
Desktop styling adjustments

### ISSUE THREAD

**Issue by mia-jane** [mia-jane/sunnyside-agency-landing-page#14]
## Tasks

- [x] render appropriate images to the screen size (mobile sized images vs desktop sized)
- [x] fix down arrow position on the header
- [x] display page links in the navbar instead of in the dropdown
- [ ] adjust dimensions to fit screen size beyond 1440px 

**time estimate** - 4 hours
