### ISSUE TITLE
Create mobile menu dropdown

### ISSUE THREAD

**Issue by mia-jane** [mia-jane/sunnyside-agency-landing-page#7]
The user should be able to click on the dropdown icon and see the navigation menu

## Tasks

- [x] make dropdown icon
- [x] css style the dropdown box and menu
- [x] toggle dropdown menu visibility on click of the dropdown icon
- [ ] add triangle pointy bit on the top of the menu

<img width="351" alt="Screen Shot 2021-07-01 at 12 21 32 PM" src="https://user-images.githubusercontent.com/54211649/124157610-f3fe9800-da66-11eb-8111-821d23672830.png">

**Time estimate** - 4 hours

**Comment by mia-jane** [comment]
Current time is 1 hr 44 min (everything is complete except the pointed corner)
